# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7832a611e46bd296ba981fd2faa397ac1fedd1f55f6943a63389001b6df7389b5c576e9fd40f2e1460688721c6886163f9491fcecf56ddab7f4ead23482e2d6

test:
  secret_key_base: dcfc99072eaa4d0f9eca5a1906b1b71869283d6a351fef36483169f3df1c34f598ae0446bcd4f28db52d066f5628ec74902296f383b02d8cab0e994d283f4213

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
